/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "bg-brand-600",
    "text-ink", 
    "bg-surface",
    "border-brand-700",
    "bg-brand-500",
    "text-brand-500",
    "border-brand-500",
    "bg-brand-secondary",
    "text-brand-primary",
    "border-brand-primary",
    "bg-brand-background-light",
    "text-brand-text",
    "text-brand-text-muted",
    "text-brand-text-light",
    "border-brand-border",
    "bg-brand-background",
    "bg-brand-background-dark",
    "ring-1",
    "ring-black/5",
    "gap-6",
    "gap-4",
    "text-green-600",
    "text-red-600",
    "sm:grid-cols-3",
    "responsive-image",
    "dotty-word",
    "pill-mobile",
    "hero-pill",
    "btn-mobile",
    "clamp-2-mobile",
    "body-text",
    "section-title",
    "hero-heading",
    "header-nav",
    "header-logo-img",
    "header-text",
    "hide-on-short",
    "touch-target"
  ]
};
