/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "bg-brand-600",
    "text-ink",
    "bg-surface",
    "border-brand-700",
    "bg-brand-500",
    "text-brand-500",
    "border-brand-500",
    "bg-brand-secondary",
    "text-brand-primary",
    "border-brand-primary",
    "bg-brand-background-light",
    "text-brand-text",
    "text-brand-text-muted",
    "text-brand-text-light",
    "border-brand-border",
    "bg-brand-background",
    "bg-brand-background-dark",
    "ring-1",
    "ring-black/5",
    "gap-6",
    "gap-4",
    "text-green-600",
    "text-red-600",
    "sm:grid-cols-3",
    "responsive-image",
    "dotty-word",
    "pill-mobile",
    "hero-pill",
    "btn-mobile",
    "clamp-2-mobile",
    "body-text",
    "section-title",
    "hero-heading",
    "header-nav",
    "header-logo-img",
    "header-text",
    "hide-on-short",
    "touch-target",

    // New: ensure button hover/active + focus-visible ring utilities are never purged
    "bg-brand-50",
    "bg-brand-100",
    "hover:bg-brand-50",
    "active:bg-brand-100",
    "text-brand-700",
    "text-brand-800",
    "hover:text-brand-800",
    "hover:border-brand-700",
    "focus-visible:ring-2",
    "focus-visible:ring-brand-primary",
    "focus-visible:ring-offset-2",
    "focus-visible:ring-offset-white",

    // New utility classes
    "btn-primary",
    "btn-secondary",
    "btn-ghost",
    "btn-danger",
    "btn-sm",
    "btn-default",
    "btn-lg",
    "btn-xl",
    "card",
    "card-elevated",
    "card-light",
    "pill",
    "pill-hero",
    "section-padding-sm",
    "section-padding-default",
    "section-padding-lg",
    "section-padding-xl",
    "text-hero-heading",
    "text-section-title",
    "text-subheading",
    "text-body",
    "text-accent-price",
    "container-default",
    "container-narrow",
    "container-wide",
    "bg-section-white",
    "bg-section-light",
    "bg-section-dark",
    "focus-ring",
    "animate-fade-in-up",
    "animate-hover-lift",
    "texture-overlay",
    "texture-overlay-soft",

    // Component-specific classes added during CSS hygiene audit
    "hero-pattern-bg",
    "dotty-word",
    "dotty-word-letter",
    "dotty-word-dot",
    "promo-card",
    "promo-card-overlay",
    "promo-card-ribbon",
  ],
};
